Add replay protection feature
firebase/firebase-admin-go pull request #641
Opened 2024-09-08 12:08 UTC by agbaraka

Hello Team.

Kindly assist to review this initial implementation of App Check Replay Protection API as requested in issue [#632](https://github.com/firebase/firebase-admin-go/issues/632).

Your feedback and guidance will be highly appreciated.

2024-09-09 19:53 UTC, weixifan reviewed
Thank you for this contribution! I have left comments addressing App Check domain-specific concerns, but I will leave it to other reviewers to address Go language style and library use concerns.

2024-09-09 19:53 UTC, weixifan commented on appcheck/appcheck.go
> +		return nil, fmt.Errorf("failed to verify token: %v", err)
Since `err` already contains information on why the token is invalid, there is no need to add a prefix. Please return `err` directly.

2024-09-09 19:53 UTC, weixifan commented on appcheck/appcheck_test.go
> +		Audience:  jwt.ClaimStrings([]string{"projects/" + projectID}),
[nit] Real App Check tokens will contain two elements in its `aud` claim: `projects/<project_number>` and `projects/<project_id>`, in that order.

2024-09-09 19:53 UTC, weixifan commented on appcheck/appcheck_test.go
> +		Subject:   "12345678:app:ID",
Please use `1:12345678:android:abcdef`.

2024-09-10 18:23 UTC, agbaraka commented on appcheck/appcheck.go
> +		verifyAppCheckTokenURL: fmt.Sprintf("%sv1beta/projects/%s:verifyAppCheckToken", appCheckIssuer, conf.ProjectID),
Hi @weixifan.

Unlike `JKWUrl`, token verification url requires requires a project ID as a parameter (i.e `https://firebaseappcheck.googleapis.com/v1beta/projects/{projectId}:verifyAppCheckToken` ), I have created a `tokenVerificationUrlFormat` which is used to initialise a `Client.tokenVerificationUrl` with project ID when initialising client instance using `NewClient(...)` function.

2024-09-10 20:36 UTC, weixifan commented on appcheck/appcheck.go
> +const tokenVerificationUrlFormat = "https://firebaseappcheck.googleapis.com/v1beta/projects/%s:verifyAppCheckToken"
You are correct: this URL indeed requires a project identifier. What we can do here is separate the domain from the rest of the URL. This way, you can create a constant (maybe `tokenVerifierDomain`?) that would be identical to `appCheckIssuer` (for now), and you can refactor the rest of the path `v1beta/projects/%s:verifyAppCheckToken` inside a new helper function whose only job is to construct the full URL given a project ID.

In my opinion, the reason a helper function is better than a constant for constructing a formatted string is that the format call and the format string are in the same place, which makes the code a lot easier to read and maintain. It also explicitly tells the caller what the format string depends on (as a function parameter).

2024-09-16 18:43 UTC, agbaraka commented
Hi @weixifan and @lahirumaramba.

Any feedback on this PR?

2024-09-16 19:47 UTC, weixifan approved these changes
Sorry about the delay. This is approved from App Check's point of view. A Golang reviewer will review your PR for style and consistency with existing code.

Thank you for your contribution!

2025-04-25 05:51 UTC, sharathguvvala commented
Hi – This is a really important feature for securing backends, and I was wondering if there’s any estimated timeline for when this might be reviewed and merged?

2025-09-15 14:28 UTC, agbaraka commented
Hello,

Any updates on this?

Thanks

2025-11-28 00:02 UTC, lahirumaramba requested changes
Thank you for you contribution and thank you so much for your patience on this. We have prioritized this feature. I added a few comments. Let me know if you have any questions.

2025-11-28 00:02 UTC, lahirumaramba commented on appcheck/appcheck.go
> +const tokenVerifierBaseUrl = "https://firebaseappcheck.googleapis.com"
Let's change this to: `var verifyTokenURL = "https://firebaseappcheck.googleapis.com/v1beta/projects/%s:verifyAppCheckToken"`

then you can simplify the URL generation to `url := fmt.Sprintf(verifyTokenURL, c.projectID)`

2025-11-28 00:02 UTC, lahirumaramba commented on appcheck/appcheck.go
> +func (c *Client) VerifyOneTimeToken(token string) (*DecodedAppCheckToken, error) {
Missing `Context`. Please change this to: `func (c *Client) VerifyOneTimeToken(ctx context.Context, token string) (*DecodedAppCheckToken, error) {`
```suggestion
func (c *Client) VerifyOneTimeToken(ctx context.Context, token string) (*DecodedAppCheckToken, error) {
```

2025-11-28 00:02 UTC, lahirumaramba commented on appcheck/appcheck.go
> +	bodyReader := bytes.NewReader([]byte(fmt.Sprintf(`{"app_check_token":%s}`, token)))
Instead of inserting the token string directly build the request object as below:
```go
url := fmt.Sprintf(verifyTokenURL, c.projectID)
reqBody := map[string]string{
	"app_check_token": token,
}
```

2025-11-28 00:02 UTC, lahirumaramba commented on appcheck/appcheck.go
> +	resp, err := http.Post(c.tokenVerifierUrl, "application/json", bodyReader)
Instead of using the default http client please use the`internal.HTTPClient` or `internal.NewHTTPClient`
see the comment above on how to inject this into `&Client`

```go
if _, err := c.httpClient.DoAndUnmarshal(ctx, req, &resp); err != nil {
	return nil, err
}
```

2025-11-28 00:02 UTC, lahirumaramba commented on appcheck/appcheck.go
> +func (c *Client) VerifyOneTimeToken(token string) (*DecodedAppCheckToken, error) {
See my comments inline, but this function should look similar to something like this:

```go
func (c *Client) VerifyOneTimeToken(ctx context.Context, token string) (*DecodedAppCheckToken, error) {
	decodedToken, err := c.VerifyToken(token)
	if err != nil {
		return nil, err
	}

	url := fmt.Sprintf(verifyTokenURL, c.projectID)
	reqBody := map[string]string{
		"app_check_token": token,
	}
	var resp struct {
		AlreadyConsumed bool `json:"alreadyConsumed"`
	}

	req := &internal.Request{
		Method: "POST",
		URL:    url,
		Body:   internal.NewJSONEntity(reqBody),
	}
	if _, err := c.httpClient.DoAndUnmarshal(ctx, req, &resp); err != nil {
		return nil, err
	}

	decodedToken.AlreadyConsumed = &resp.AlreadyConsumed
	return decodedToken, nil
}
```

2025-11-28 00:02 UTC, lahirumaramba commented on appcheck/appcheck.go
> +		tokenVerifierUrl: buildTokenVerifierUrl(conf.ProjectID),
Instead of passing the URL you can pass the http client here and build the URL in `VerifyOneTimeToken` (see the comment below on that)
```go
hc, _, err := internal.NewHTTPClient(ctx, conf.Opts...)
if err != nil {
	return nil, err
}

return &Client{
	projectID:  conf.ProjectID,
	jwks:       jwks,
	httpClient: hc,
}, nil
```

2025-11-28 00:02 UTC, lahirumaramba commented on appcheck/appcheck.go
> +	tokenVerifierUrl string
```
type Client struct {
	projectID  string
	jwks       *keyfunc.JWKS
	httpClient *internal.HTTPClient
}
```

2025-11-28 00:11 UTC, lahirumaramba commented on appcheck/appcheck.go
> +		tokenVerifierUrl: buildTokenVerifierUrl(conf.ProjectID),
For this to work correctly you will also need to update the following:

`AppCheckConfig struct` in `firebase-admin-go/internal/internal.go`
```go
type AppCheckConfig struct {
	Opts      []option.ClientOption // <----------------
	ProjectID string
}
```

`func (a *App) AppCheck(ctx context.Context) (*appcheck.Client, error) {` in `firebase-admin-go/firebase.go`
```go
func (a *App) AppCheck(ctx context.Context) (*appcheck.Client, error) {
	conf := &internal.AppCheckConfig{
		ProjectID: a.projectID,
		Opts:      a.opts, // <-------------------
	}
	return appcheck.NewClient(ctx, conf)
}
```

2025-11-30 08:20 UTC, agbaraka commented
Hello @lahirumaramba. Thank you very much for your feedback. I have added another commit with include changes from your comments.

I had to also update `TestVerifyOneTimeToken`. Kindly assist to review

Thanks

2025-12-01 16:42 UTC, lahirumaramba commented on go.mod
> +go 1.24.0
Thank you for the updates! Are you able to remove `go.mod` and `go.sum` files from this PR? We like to keep dependency updates in separate PRs when we can.

2025-12-01 17:30 UTC, agbaraka commented on go.mod
> +go 1.24.0
Hi @lahirumaramba.

The changes originated from upstream dev branch. Should i proceed with reverting the changes or simply revert go.mod and go.sum changes only?

2025-12-01 19:08 UTC, lahirumaramba commented on go.mod
> +go 1.24.0
Interesting... the dev branch is still on `1.23.0` https://github.com/firebase/firebase-admin-go/blob/da7068d6d46f07b69052c691949a7e65049df7a0/go.mod#L3

I think you can just revert `go.mod` and `go.sum` from this PR. Please also fix the lint error. Thank you!

2025-12-01 19:09 UTC, lahirumaramba commented on go.mod
> +go 1.24.0
`Error: appcheck/appcheck_test.go:74:4: var mockHttpClient should be mockHTTPClient`

2025-12-01 19:10 UTC, lahirumaramba requested changes

2025-12-01 19:10 UTC, lahirumaramba commented on appcheck/appcheck_test.go
> +			mockHttpClient := &http.Client{
```suggestion
			mockHTTPClient := &http.Client{
```

2025-12-01 19:52 UTC, agbaraka commented
Hi @lahirumaramba 

I have updated as per the above feedback.

Thank you for your assistance

2025-12-01 22:16 UTC, lahirumaramba commented
@gemini-code-assist review

2025-12-02 19:27 UTC, agbaraka commented
Hi @lahirumaramba and team.

Kindly advise on the failed test stage.

Thanks

2025-12-04 17:59 UTC, agbaraka commented
Hello @lahirumaramba and @weixifan.

I hope all is well.

I have updated the pull request to fix bugs in the test file.

Kindly assist to review and approve

2025-12-04 20:05 UTC, agbaraka commented on appcheck/appcheck_test.go
> +	}
@lahirumaramba and @weixifan. This has been addressed on the latest commit

2026-08-11 13:30 UTC, yvonnep165 commented
Hi @agbaraka , Thank you so much for your work on this PR and for laying the groundwork for App Check replay protection!

We are completing the implementation in [#774](https://github.com/firebase/firebase-admin-go/pull/774) to align with the API design for `VerifyOneTimeToken`. 

We want to ensure you get full credit for your contribution, so we’ve merged your PR history into [#774](https://github.com/firebase/firebase-admin-go/pull/774) so your work remains recorded in the Git history and release notes.

I’ll go ahead and close this PR in favor of [#774](https://github.com/firebase/firebase-admin-go/pull/774). Thanks again for your support and contributions!

2026-08-11 13:32 UTC, closed without merging